PACKAGE_NAME="metis"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="metis"
DEST_MODULE_LOCATION[0]="/extra"

AUTOINSTALL="yes"

MAKE[0]="make KERNELDIR=/lib/modules/${kernelver}/build"
CLEAN="make clean"

# Optional but recommended
REMAKE_INITRD="no"
